syntax = "proto3";

option go_package = "./pbConsumer";
package pbConsumer;

// Service for Register and Authentication of Consumers, Productors
service Consumer {
    rpc GetEvents(GetEventsRequest) returns (GetEventsResponse);
    rpc PurchaseEvent(PurchaseEventRequest) returns (PurchaseEventResponse);
}

message GetEventsRequest {
    string uuid = 1;
}

message Event {
    string eventID = 1;
    string discoteca = 2;
    string nombreEvento = 3;
    string categoria = 4;
    string comuna = 5;
    int32 precio = 6;
    int32 stock = 7;
    int32 spendStock = 8;
    string fechaEvento = 9;
    string fechaPublicacion = 10;
}

message GetEventsResponse {
    bool succes = 1;
    string message = 2;
    repeated Event events = 3;
}

message PurchaseEventRequest {
    string uuid = 1;
    string eventID = 2;
    string paymentMethod = 3; // e.g. "debito", "credito"
    int32 quantity = 4;
}

message PurchaseEventResponse {
    bool succes = 1;
    string message = 2;
    string ticketID = 3;
}