// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: Banco/proto/pbBancoUSM.proto

package pbBancoUSM

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BancoUSM_ProcessPayment_FullMethodName = "/pbBancoUSM.BancoUSM/ProcessPayment"
)

// BancoUSMClient is the client API for BancoUSM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BancoUSMClient interface {
	ProcessPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
}

type bancoUSMClient struct {
	cc grpc.ClientConnInterface
}

func NewBancoUSMClient(cc grpc.ClientConnInterface) BancoUSMClient {
	return &bancoUSMClient{cc}
}

func (c *bancoUSMClient) ProcessPayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, BancoUSM_ProcessPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BancoUSMServer is the server API for BancoUSM service.
// All implementations must embed UnimplementedBancoUSMServer
// for forward compatibility.
type BancoUSMServer interface {
	ProcessPayment(context.Context, *PaymentRequest) (*PaymentResponse, error)
	mustEmbedUnimplementedBancoUSMServer()
}

// UnimplementedBancoUSMServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBancoUSMServer struct{}

func (UnimplementedBancoUSMServer) ProcessPayment(context.Context, *PaymentRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPayment not implemented")
}
func (UnimplementedBancoUSMServer) mustEmbedUnimplementedBancoUSMServer() {}
func (UnimplementedBancoUSMServer) testEmbeddedByValue()                  {}

// UnsafeBancoUSMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BancoUSMServer will
// result in compilation errors.
type UnsafeBancoUSMServer interface {
	mustEmbedUnimplementedBancoUSMServer()
}

func RegisterBancoUSMServer(s grpc.ServiceRegistrar, srv BancoUSMServer) {
	// If the following call panics, it indicates UnimplementedBancoUSMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BancoUSM_ServiceDesc, srv)
}

func _BancoUSM_ProcessPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BancoUSMServer).ProcessPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BancoUSM_ProcessPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BancoUSMServer).ProcessPayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BancoUSM_ServiceDesc is the grpc.ServiceDesc for BancoUSM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BancoUSM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbBancoUSM.BancoUSM",
	HandlerType: (*BancoUSMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPayment",
			Handler:    _BancoUSM_ProcessPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Banco/proto/pbBancoUSM.proto",
}
