// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: Banco/proto/pbBancoUSM.proto

package pbBancoUSM

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"` // e.g. "debito", "credito"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_Banco_proto_pbBancoUSM_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Banco_proto_pbBancoUSM_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_Banco_proto_pbBancoUSM_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PaymentRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_Banco_proto_pbBancoUSM_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Banco_proto_pbBancoUSM_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_Banco_proto_pbBancoUSM_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_Banco_proto_pbBancoUSM_proto protoreflect.FileDescriptor

const file_Banco_proto_pbBancoUSM_proto_rawDesc = "" +
	"\n" +
	"\x1cBanco/proto/pbBancoUSM.proto\x12\n" +
	"pbBancoUSM\"b\n" +
	"\x0ePaymentRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12$\n" +
	"\rpaymentMethod\x18\x03 \x01(\tR\rpaymentMethod\"E\n" +
	"\x0fPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2U\n" +
	"\bBancoUSM\x12I\n" +
	"\x0eProcessPayment\x12\x1a.pbBancoUSM.PaymentRequest\x1a\x1b.pbBancoUSM.PaymentResponseB\x0eZ\f./pbBancoUSMb\x06proto3"

var (
	file_Banco_proto_pbBancoUSM_proto_rawDescOnce sync.Once
	file_Banco_proto_pbBancoUSM_proto_rawDescData []byte
)

func file_Banco_proto_pbBancoUSM_proto_rawDescGZIP() []byte {
	file_Banco_proto_pbBancoUSM_proto_rawDescOnce.Do(func() {
		file_Banco_proto_pbBancoUSM_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Banco_proto_pbBancoUSM_proto_rawDesc), len(file_Banco_proto_pbBancoUSM_proto_rawDesc)))
	})
	return file_Banco_proto_pbBancoUSM_proto_rawDescData
}

var file_Banco_proto_pbBancoUSM_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Banco_proto_pbBancoUSM_proto_goTypes = []any{
	(*PaymentRequest)(nil),  // 0: pbBancoUSM.PaymentRequest
	(*PaymentResponse)(nil), // 1: pbBancoUSM.PaymentResponse
}
var file_Banco_proto_pbBancoUSM_proto_depIdxs = []int32{
	0, // 0: pbBancoUSM.BancoUSM.ProcessPayment:input_type -> pbBancoUSM.PaymentRequest
	1, // 1: pbBancoUSM.BancoUSM.ProcessPayment:output_type -> pbBancoUSM.PaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Banco_proto_pbBancoUSM_proto_init() }
func file_Banco_proto_pbBancoUSM_proto_init() {
	if File_Banco_proto_pbBancoUSM_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Banco_proto_pbBancoUSM_proto_rawDesc), len(file_Banco_proto_pbBancoUSM_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Banco_proto_pbBancoUSM_proto_goTypes,
		DependencyIndexes: file_Banco_proto_pbBancoUSM_proto_depIdxs,
		MessageInfos:      file_Banco_proto_pbBancoUSM_proto_msgTypes,
	}.Build()
	File_Banco_proto_pbBancoUSM_proto = out.File
	file_Banco_proto_pbBancoUSM_proto_goTypes = nil
	file_Banco_proto_pbBancoUSM_proto_depIdxs = nil
}
