services:
  banco:
    build:
      context: ./Banco
    container_name: banco-container
    ports:
      - "5000:5000"
    volumes:
      - ./Banco/keys:/app/keys
    environment:
      - "NAME=Banco"
      - "PORT=5000"
      - "BROKER_URL=broker:5001"
      - "MYDIRECTION=banco:5000"
    networks:
      default:
        aliases:
          - "banco"

  broker:
    build:
      context: ./Broker
    container_name: broker-container
    ports:
      - "5001:5001"
    environment:
      - "NAME=Broker"
      - "PORT=5001"
    networks:
      default:
        aliases:
          - "broker"
  consumidor1:
    build:
      context: ./Consumidor
    ports:
      - "5002-5009:5002"
    volumes:
      - ./Consumidor/keys:/app/keys
    environment:
      - "NAME=Consumidor1"
      - "PORT=5002"
      - "BROKER_URL=broker:5001"

  consumidor2:
    build:
      context: ./Consumidor
    ports:
      - "5002-5009:5002"
    volumes:
      - ./Consumidor/keys:/app/keys
    environment:
      - "NAME=Consumidor2"
      - "PORT=5002"
      - "BROKER_URL=broker:5001"
    
  productor1:
    build:
      context: ./Productor
    ports:
      - "5003-5009:5003"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=DataClub"
      - "PORT=5003"
      - "BROKER_URL=broker:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"

  productor2:
    build:
      context: ./Productor
    ports:
      - "5003-5009:5003"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=Dockers Night"
      - "PORT=5003"
      - "BROKER_URL=broker:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"
    
  productor3:
    build:
      context: ./Productor
    ports:
      - "5003-5009:5003"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=GoLounge"
      - "PORT=5003"
      - "BROKER_URL=broker:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"

  productor4:
    build:
      context: ./Productor
    ports:
      - "5003-5009:5003"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=GeorgieHouse"
      - "PORT=5003"
      - "BROKER_URL=broker:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"

  dynamodb1:
    build:
      context: ./DynamoDB
    ports:
      - "8001:8000"
    volumes:
      - ./DynamoDB/keys:/app/keys
      - ./DynamoDB/Data:/app/Data
    environment:
      - "NAME=DynamoDB-1"
      - "PORT=8000"
      - "BROKER_URL=broker:5001"
      - "MYDIRECTION=dynamodb-1:8001"
    networks:
      default:
        aliases:
          - "dynamodb-1"

  dynamodb2:
    build:
      context: ./DynamoDB
    ports:
      - "8002:8000"
    volumes:
      - ./DynamoDB/keys:/app/keys
      - ./DynamoDB/Data:/app/Data
    environment:
      - "NAME=DynamoDB-2"
      - "PORT=8000"
      - "BROKER_URL=broker:5001"
      - "MYDIRECTION=dynamodb-2:8002"
    networks:
      default:
        aliases:
          - "dynamodb-2"

  dynamodb3:
    build:
      context: ./DynamoDB
    ports:
      - "8003:8000"
    volumes:
      - ./DynamoDB/keys:/app/keys
      - ./DynamoDB/Data:/app/Data
    environment:
      - "NAME=DynamoDB-3"
      - "PORT=8000"
      - "BROKER_URL=broker:5001"
      - "MYDIRECTION=dynamodb-3:8003"
    networks:
      default:
        aliases:
          - "dynamodb-3"