services:
  banco:
    build:
      context: ./Banco
    container_name: banco-container
    ports:
      - "5000:5000"
    environment:
      - "NAME=Banco"
      - "PORT=5000"
      - "BROKER_URL=broker:5001"
    networks:
      default:
        aliases:
          - "banco"

  broker:
    build:
      context: ./Broker
    container_name: broker-container
    ports:
      - "5001:5001"
    environment:
      - "NAME=Broker"
      - "PORT=5001"
    networks:
      default:
        aliases:
          - "broker"

  consumidor:
    build:
      context: ./Consumidor
    container_name: consumidor-container
    ports:
      - "5002:5002"
    environment:
      - "NAME=Consumidor"
      - "PORT=5002"
      - "BROKER_URL=broker:5001"
    networks:
      default:
        aliases:
          - "consumidor"

  dynamodb:
    build:
      context: ./DynamoDB
    container_name: dynamodb-container
    ports:
      - "8000-8010:8000"
    environment:
      - "NAME=DynamoDB"
      - "PORT=8000"
    networks:
      default:
        aliases:
          - "dynamodb"