services:
  broker:
    build:
      context: ./Broker
    container_name: broker
    ports:
      - "5001:5001"
    environment:
      - "NAME=Broker"
      - "PORT=5001"
    networks:
      default:
        aliases:
          - "broker"

  banco:
    build:
      context: ./Banco
    container_name: banco
    ports:
      - "5000:5000"
    volumes:
      - ./Banco/Logs:/app/Logs
    environment:
      - "NAME=Banco"
      - "PORT=5000"
      - "BROKER_URL=10.35.168.35:5001"
      - "MYDIRECTION=10.35.168.38:5000"
    networks:
      default:
        aliases:
          - "banco"

  consumer1:
    build:
      context: ./Consumer
    container_name: consumer-1
    ports:
      - "6001:6001"
    volumes:
      - ./Consumer/keys:/app/keys
      - ./Consumer/output:/app/output
    environment:
      - "NAME=user_1"
      - "PORT=6001"
      - "BROKER_URL=10.35.168.35:5001"

  consumer2:
    build:
      context: ./Consumer
    container_name: consumer-2
    ports:
      - "6002:6002"
    volumes:
      - ./Consumer/keys:/app/keys
      - ./Consumer/output:/app/output
    environment:
      - "NAME=user_2"
      - "PORT=6002"
      - "BROKER_URL=10.35.168.35:5001"

  productor1:
    build:
      context: ./Productor
    container_name: productor-1
    ports:
      - "5006:5006"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=DataClub"
      - "PORT=5006"
      - "BROKER_URL=10.35.168.35:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"

  productor2:
    build:
      context: ./Productor
    container_name: productor-2
    ports:
      - "5007:5007"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=Dockers Night"
      - "PORT=5007"
      - "BROKER_URL=10.35.168.35:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"
    
  productor3:
    build:
      context: ./Productor
    container_name: productor-3
    ports:
      - "5008:5008"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=GoLounge"
      - "PORT=5008"
      - "BROKER_URL=10.35.168.35:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"

  productor4:
    build:
      context: ./Productor
    container_name: productor-4
    ports:
      - "5009:5009"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=GeorgieHouse"
      - "PORT=5009"
      - "BROKER_URL=10.35.168.35:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"
  node1:
    build:
      context: ./DynamoDB
    container_name: node-1
    ports:
      - "8001:8001"
    volumes:
      - ./DynamoDB/Data:/app/Data
    environment:
      - "NAME=DynamoDB-1"
      - "PORT=8001"
      - "BROKER_URL=10.35.168.35:5001"
      - "MYDIRECTION=10.35.168.38:8001"
    networks:
      default:
        aliases:
          - "node1"

  node2:
    build:
      context: ./DynamoDB
    container_name: node-2
    ports:
      - "8002:8002"
    volumes:
      - ./DynamoDB/Data:/app/Data
    environment:
      - "NAME=DynamoDB-2"
      - "PORT=8002"
      - "BROKER_URL=10.35.168.35:5001"
      - "MYDIRECTION=10.35.168.37:8002"
    networks:
      default:
        aliases:
          - "node2"

  node3:
    build:
      context: ./DynamoDB
    container_name: node-3
    ports:
      - "8003:8003"
    volumes:
      - ./DynamoDB/Data:/app/Data
    environment:
      - "NAME=DynamoDB-3"
      - "PORT=8003"
      - "BROKER_URL=10.35.168.35:5001"
      - "MYDIRECTION=10.35.168.36:8003"
    networks:
      default:
        aliases:
          - "node3"

  chaos-node1:
    image: docker:cli
    container_name: chaos-node1
    depends_on:
      - node1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["sh", "-c"]
    command: >
      "
      echo 'Chaos: waiting before taking node1 down...';
      sleep $$((RANDOM % 50 + 20));
      echo 'Chaos: stopping node1';
      docker pause node-1;
      sleep $$((RANDOM % 15 + 5));
      echo 'Chaos: restarting node1';
      docker unpause node-1;
      echo 'Chaos: done'
      "
  chaos-node2:
    image: docker:cli
    container_name: chaos-node2
    depends_on:
      - node2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["sh", "-c"]
    command: >
      "
      echo 'Chaos: waiting before taking node-2 down...';
      sleep $$((RANDOM % 50 + 60));
      echo 'Chaos: pausing node-2';
      docker pause node-2;
      sleep $$((RANDOM % 15 + 5));
      echo 'Chaos: restarting node-2';
      docker unpause node-2;
      echo 'Chaos: done'
      "

  chaos-node3:
    image: docker:cli
    container_name: chaos-node3
    depends_on:
      - node3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["sh", "-c"]
    command: >
      "
      echo 'Chaos: waiting before taking node-3 down...';
      sleep $$((RANDOM % 50 + 50));
      echo 'Chaos: stopping node-3';
      docker pause node-3;
      sleep $$((RANDOM % 15 + 5));
      echo 'Chaos: restarting node1';
      docker unpause node-3;
      echo 'Chaos: done'
      "
  chaos-banco:
    image: docker:cli
    container_name: chaos-banco
    depends_on:
      - banco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["sh", "-c"]
    command: >
      "
      echo 'Chaos: waiting before taking banco down...';
      sleep $$((RANDOM % 50 + 60));
      echo 'Chaos: stopping banco';
      docker pause banco;
      sleep $$((RANDOM % 15 + 5));
      echo 'Chaos: restarting banco';
      docker unpause banco;
      echo 'Chaos: done'
      "

  chaos-consumer:
    image: docker:cli
    container_name: chaos-consumer
    depends_on:
      - consumer1
      - consumer2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["sh", "-c"]
    command: >
      "
      echo 'Chaos: waiting before taking consumer-1 down...';
      sleep $$((RANDOM % 50 + 60));
      echo 'Chaos: stopping consumer-1';
      docker pause consumer-1;
      sleep $$((RANDOM % 15 + 5));
      echo 'Chaos: restarting consumer-1';
      docker unpause consumer-1;
      echo 'Chaos: waiting before taking consumer-2 down...';
      sleep $$((RANDOM % 50 + 60));
      echo 'Chaos: stopping consumer-2';
      docker pause consumer-2;
      sleep $$((RANDOM % 15 + 5));
      echo 'Chaos: restarting consumer-2';
      docker unpause consumer-2;
      echo 'Chaos: done'
      "