services:
  broker:
    build:
      context: ./Broker
    container_name: broker-container
    ports:
      - "5001:5001"
    environment:
      - "NAME=Broker"
      - "PORT=5001"
    networks:
      default:
        aliases:
          - "broker"

  banco:
    build:
      context: ./Banco
    container_name: banco-container
    ports:
      - "5000:5000"
    volumes:
      - ./Banco/Logs:/app/Logs
    environment:
      - "NAME=Banco"
      - "PORT=5000"
      - "BROKER_URL=broker:5001"
      - "MYDIRECTION=banco:5000"
    networks:
      default:
        aliases:
          - "banco"

  consumer1:
    build:
      context: ./Consumer
    ports:
      - "6001-6002:6000"
    volumes:
      - ./Consumer/keys:/app/keys
      - ./Consumer/output:/app/output
    environment:
      - "NAME=user_1"
      - "PORT=6000"
      - "BROKER_URL=broker:5001"

  consumer2:
    build:
      context: ./Consumer
    ports:
      - "6001-6002:6000"
    volumes:
      - ./Consumer/keys:/app/keys
      - ./Consumer/output:/app/output
    environment:
      - "NAME=user_2"
      - "PORT=6000"
      - "BROKER_URL=broker:5001"

  productor1:
    build:
      context: ./Productor
    ports:
      - "5003-5009:5003"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=DataClub"
      - "PORT=5003"
      - "BROKER_URL=broker:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"

  productor2:
    build:
      context: ./Productor
    ports:
      - "5003-5009:5003"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=Dockers Night"
      - "PORT=5003"
      - "BROKER_URL=broker:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"
    
  productor3:
    build:
      context: ./Productor
    ports:
      - "5003-5009:5003"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=GoLounge"
      - "PORT=5003"
      - "BROKER_URL=broker:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"

  productor4:
    build:
      context: ./Productor
    ports:
      - "5003-5009:5003"
    volumes:
      - ./Productor/keys:/app/keys
      - ./Productor/input:/app/input
    environment:
      - "NAME=GeorgieHouse"
      - "PORT=5003"
      - "BROKER_URL=broker:5001"
      - "INPUT_FILE=catalogo_eventos_30.json"
  node1:
    build:
      context: ./DynamoDB
    container_name: node1
    ports:
      - "8001:8001"
    volumes:
      - ./DynamoDB/Data:/app/Data
    environment:
      - "NAME=DynamoDB-1"
      - "PORT=8001"
      - "BROKER_URL=broker:5001"
      - "MYDIRECTION=node1:8001"
    networks:
      default:
        aliases:
          - "node1"

  node2:
    build:
      context: ./DynamoDB
    container_name: node2
    ports:
      - "8002:8000"
    volumes:
      - ./DynamoDB/Data:/app/Data
    environment:
      - "NAME=DynamoDB-2"
      - "PORT=8002"
      - "BROKER_URL=broker:5001"
      - "MYDIRECTION=node2:8002"
    networks:
      default:
        aliases:
          - "node2"

  node3:
    build:
      context: ./DynamoDB
    container_name: node3
    ports:
      - "8003:8000"
    volumes:
      - ./DynamoDB/Data:/app/Data
    environment:
      - "NAME=DynamoDB-3"
      - "PORT=8003"
      - "BROKER_URL=broker:5001"
      - "MYDIRECTION=node3:8003"
    networks:
      default:
        aliases:
          - "node3"