// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: Broker/proto/pbDynamoDB.proto

package pbDynamoDB

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DynamoDB_CheckIsAlive_FullMethodName = "/pbDynamoDB.DynamoDB/CheckIsAlive"
	DynamoDB_CreateTable_FullMethodName  = "/pbDynamoDB.DynamoDB/CreateTable"
	DynamoDB_PutItem_FullMethodName      = "/pbDynamoDB.DynamoDB/PutItem"
	DynamoDB_GetItem_FullMethodName      = "/pbDynamoDB.DynamoDB/GetItem"
	DynamoDB_GetTable_FullMethodName     = "/pbDynamoDB.DynamoDB/GetTable"
	DynamoDB_SyncAllData_FullMethodName  = "/pbDynamoDB.DynamoDB/SyncAllData"
	DynamoDB_GetAllData_FullMethodName   = "/pbDynamoDB.DynamoDB/GetAllData"
)

// DynamoDBClient is the client API for DynamoDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynamoDBClient interface {
	CheckIsAlive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IsAliveResponde, error)
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error)
	PutItem(ctx context.Context, in *PutItemRequest, opts ...grpc.CallOption) (*PutItemResponse, error)
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*GetTableResponse, error)
	SyncAllData(ctx context.Context, in *SyncAllDataRequest, opts ...grpc.CallOption) (*SyncAllDataResponse, error)
	GetAllData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllDataResponse, error)
}

type dynamoDBClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamoDBClient(cc grpc.ClientConnInterface) DynamoDBClient {
	return &dynamoDBClient{cc}
}

func (c *dynamoDBClient) CheckIsAlive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IsAliveResponde, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAliveResponde)
	err := c.cc.Invoke(ctx, DynamoDB_CheckIsAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoDBClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, DynamoDB_CreateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoDBClient) PutItem(ctx context.Context, in *PutItemRequest, opts ...grpc.CallOption) (*PutItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutItemResponse)
	err := c.cc.Invoke(ctx, DynamoDB_PutItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoDBClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, DynamoDB_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoDBClient) GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*GetTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableResponse)
	err := c.cc.Invoke(ctx, DynamoDB_GetTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoDBClient) SyncAllData(ctx context.Context, in *SyncAllDataRequest, opts ...grpc.CallOption) (*SyncAllDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncAllDataResponse)
	err := c.cc.Invoke(ctx, DynamoDB_SyncAllData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamoDBClient) GetAllData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllDataResponse)
	err := c.cc.Invoke(ctx, DynamoDB_GetAllData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamoDBServer is the server API for DynamoDB service.
// All implementations must embed UnimplementedDynamoDBServer
// for forward compatibility.
type DynamoDBServer interface {
	CheckIsAlive(context.Context, *Empty) (*IsAliveResponde, error)
	CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	PutItem(context.Context, *PutItemRequest) (*PutItemResponse, error)
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	GetTable(context.Context, *GetTableRequest) (*GetTableResponse, error)
	SyncAllData(context.Context, *SyncAllDataRequest) (*SyncAllDataResponse, error)
	GetAllData(context.Context, *Empty) (*GetAllDataResponse, error)
	mustEmbedUnimplementedDynamoDBServer()
}

// UnimplementedDynamoDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynamoDBServer struct{}

func (UnimplementedDynamoDBServer) CheckIsAlive(context.Context, *Empty) (*IsAliveResponde, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIsAlive not implemented")
}
func (UnimplementedDynamoDBServer) CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedDynamoDBServer) PutItem(context.Context, *PutItemRequest) (*PutItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutItem not implemented")
}
func (UnimplementedDynamoDBServer) GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedDynamoDBServer) GetTable(context.Context, *GetTableRequest) (*GetTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTable not implemented")
}
func (UnimplementedDynamoDBServer) SyncAllData(context.Context, *SyncAllDataRequest) (*SyncAllDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncAllData not implemented")
}
func (UnimplementedDynamoDBServer) GetAllData(context.Context, *Empty) (*GetAllDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllData not implemented")
}
func (UnimplementedDynamoDBServer) mustEmbedUnimplementedDynamoDBServer() {}
func (UnimplementedDynamoDBServer) testEmbeddedByValue()                  {}

// UnsafeDynamoDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamoDBServer will
// result in compilation errors.
type UnsafeDynamoDBServer interface {
	mustEmbedUnimplementedDynamoDBServer()
}

func RegisterDynamoDBServer(s grpc.ServiceRegistrar, srv DynamoDBServer) {
	// If the following call panics, it indicates UnimplementedDynamoDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DynamoDB_ServiceDesc, srv)
}

func _DynamoDB_CheckIsAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoDBServer).CheckIsAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoDB_CheckIsAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoDBServer).CheckIsAlive(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamoDB_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoDBServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoDB_CreateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoDBServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamoDB_PutItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoDBServer).PutItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoDB_PutItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoDBServer).PutItem(ctx, req.(*PutItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamoDB_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoDBServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoDB_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoDBServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamoDB_GetTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoDBServer).GetTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoDB_GetTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoDBServer).GetTable(ctx, req.(*GetTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamoDB_SyncAllData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncAllDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoDBServer).SyncAllData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoDB_SyncAllData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoDBServer).SyncAllData(ctx, req.(*SyncAllDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamoDB_GetAllData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoDBServer).GetAllData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoDB_GetAllData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoDBServer).GetAllData(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DynamoDB_ServiceDesc is the grpc.ServiceDesc for DynamoDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynamoDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbDynamoDB.DynamoDB",
	HandlerType: (*DynamoDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIsAlive",
			Handler:    _DynamoDB_CheckIsAlive_Handler,
		},
		{
			MethodName: "CreateTable",
			Handler:    _DynamoDB_CreateTable_Handler,
		},
		{
			MethodName: "PutItem",
			Handler:    _DynamoDB_PutItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _DynamoDB_GetItem_Handler,
		},
		{
			MethodName: "GetTable",
			Handler:    _DynamoDB_GetTable_Handler,
		},
		{
			MethodName: "SyncAllData",
			Handler:    _DynamoDB_SyncAllData_Handler,
		},
		{
			MethodName: "GetAllData",
			Handler:    _DynamoDB_GetAllData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Broker/proto/pbDynamoDB.proto",
}
