syntax = "proto3";

option go_package = "./pbDynamoDB";
package pbDynamoDB;

service DynamoDB {
    rpc CheckIsAlive(Empty) returns (IsAliveResponde);
    rpc CreateTable(CreateTableRequest) returns (CreateTableResponse);
    rpc PutItem(PutItemRequest) returns (PutItemResponse);
    rpc GetItem(GetItemRequest) returns (GetItemResponse);
    rpc GetTable(GetTableRequest) returns (GetTableResponse);

    rpc SyncAllData(SyncAllDataRequest) returns (SyncAllDataResponse);
    rpc GetAllData(Empty) returns (GetAllDataResponse);
}

message Empty {

}

message IsAliveResponde {
    bool isAlive = 1;
}

message CreateTableRequest {
    string table_name = 1;
}

message CreateTableResponse {
    bool success = 1;
    string message = 2;
}

message PutItemRequest {
    string table_name = 1;
    string key = 2;
    bytes value = 3;
}

message PutItemResponse {
    bool success = 1;
    string message = 2;
}

message GetItemRequest {
    string table_name = 1;
    string key = 2;
}

message Item {
    bytes value = 1;
    bool exists = 2;
}

message GetItemResponse {
    bool success = 1;
    Item value = 2;
    string message = 3;
}

message GetTableRequest {
    string table_name = 1;
}

message GetTableResponse {
    bool success = 1;
    Table data = 2;
    string message = 3;
}

message Table {
    string name = 1;
    repeated string keys = 2;
    repeated bytes value = 3;
}

message SyncAllDataRequest {
    repeated Table allData = 1;
}

message SyncAllDataResponse {
    bool success = 1;
    string message = 2;
}

message GetAllDataResponse {
    bool success = 1;
    repeated Table allData = 2;
    string message = 3;
}