// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: Broker/proto/pbBroker.proto

package pbBroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          int32                  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbBroker_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type Event struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventID          string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	Discoteca        string                 `protobuf:"bytes,2,opt,name=discoteca,proto3" json:"discoteca,omitempty"`
	NombreEvento     string                 `protobuf:"bytes,3,opt,name=nombreEvento,proto3" json:"nombreEvento,omitempty"`
	Categoria        string                 `protobuf:"bytes,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Comuna           string                 `protobuf:"bytes,5,opt,name=comuna,proto3" json:"comuna,omitempty"`
	Precio           int32                  `protobuf:"varint,6,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock            int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	SpendStock       int32                  `protobuf:"varint,8,opt,name=spendStock,proto3" json:"spendStock,omitempty"`
	FechaEvento      string                 `protobuf:"bytes,9,opt,name=fechaEvento,proto3" json:"fechaEvento,omitempty"`
	FechaPublicacion string                 `protobuf:"bytes,10,opt,name=fechaPublicacion,proto3" json:"fechaPublicacion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbBroker_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *Event) GetDiscoteca() string {
	if x != nil {
		return x.Discoteca
	}
	return ""
}

func (x *Event) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *Event) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Event) GetComuna() string {
	if x != nil {
		return x.Comuna
	}
	return ""
}

func (x *Event) GetPrecio() int32 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Event) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Event) GetSpendStock() int32 {
	if x != nil {
		return x.SpendStock
	}
	return 0
}

func (x *Event) GetFechaEvento() string {
	if x != nil {
		return x.FechaEvento
	}
	return ""
}

func (x *Event) GetFechaPublicacion() string {
	if x != nil {
		return x.FechaPublicacion
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbBroker_proto_rawDescGZIP(), []int{2}
}

type IsAliveResponde struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAlive       bool                   `protobuf:"varint,1,opt,name=isAlive,proto3" json:"isAlive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAliveResponde) Reset() {
	*x = IsAliveResponde{}
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAliveResponde) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAliveResponde) ProtoMessage() {}

func (x *IsAliveResponde) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAliveResponde.ProtoReflect.Descriptor instead.
func (*IsAliveResponde) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbBroker_proto_rawDescGZIP(), []int{3}
}

func (x *IsAliveResponde) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	WhatIAm       string                 `protobuf:"bytes,2,opt,name=whatIAm,proto3" json:"whatIAm,omitempty"`
	Uuid          *string                `protobuf:"bytes,3,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbBroker_proto_rawDescGZIP(), []int{4}
}

func (x *HandshakeRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *HandshakeRequest) GetWhatIAm() string {
	if x != nil {
		return x.WhatIAm
	}
	return ""
}

func (x *HandshakeRequest) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UUID          *string                `protobuf:"bytes,2,opt,name=UUID,proto3,oneof" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbBroker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbBroker_proto_rawDescGZIP(), []int{5}
}

func (x *HandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandshakeResponse) GetUUID() string {
	if x != nil && x.UUID != nil {
		return *x.UUID
	}
	return ""
}

var File_Broker_proto_pbBroker_proto protoreflect.FileDescriptor

const file_Broker_proto_pbBroker_proto_rawDesc = "" +
	"\n" +
	"\x1bBroker/proto/pbBroker.proto\x12\bpbBroker\"\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x05R\x04data\"\xb5\x02\n" +
	"\x05Event\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12\x1c\n" +
	"\tdiscoteca\x18\x02 \x01(\tR\tdiscoteca\x12\"\n" +
	"\fnombreEvento\x18\x03 \x01(\tR\fnombreEvento\x12\x1c\n" +
	"\tcategoria\x18\x04 \x01(\tR\tcategoria\x12\x16\n" +
	"\x06comuna\x18\x05 \x01(\tR\x06comuna\x12\x16\n" +
	"\x06precio\x18\x06 \x01(\x05R\x06precio\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1e\n" +
	"\n" +
	"spendStock\x18\b \x01(\x05R\n" +
	"spendStock\x12 \n" +
	"\vfechaEvento\x18\t \x01(\tR\vfechaEvento\x12*\n" +
	"\x10fechaPublicacion\x18\n" +
	" \x01(\tR\x10fechaPublicacion\"\a\n" +
	"\x05Empty\"+\n" +
	"\x0fIsAliveResponde\x12\x18\n" +
	"\aisAlive\x18\x01 \x01(\bR\aisAlive\"l\n" +
	"\x10HandshakeRequest\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x18\n" +
	"\awhatIAm\x18\x02 \x01(\tR\awhatIAm\x12\x17\n" +
	"\x04uuid\x18\x03 \x01(\tH\x00R\x04uuid\x88\x01\x01B\a\n" +
	"\x05_uuid\"O\n" +
	"\x11HandshakeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\x04UUID\x18\x02 \x01(\tH\x00R\x04UUID\x88\x01\x01B\a\n" +
	"\x05_UUID2\x8a\x01\n" +
	"\x06Broker\x12:\n" +
	"\fCheckIsAlive\x12\x0f.pbBroker.Empty\x1a\x19.pbBroker.IsAliveResponde\x12D\n" +
	"\tHandshake\x12\x1a.pbBroker.HandshakeRequest\x1a\x1b.pbBroker.HandshakeResponseB\fZ\n" +
	"./pbBrokerb\x06proto3"

var (
	file_Broker_proto_pbBroker_proto_rawDescOnce sync.Once
	file_Broker_proto_pbBroker_proto_rawDescData []byte
)

func file_Broker_proto_pbBroker_proto_rawDescGZIP() []byte {
	file_Broker_proto_pbBroker_proto_rawDescOnce.Do(func() {
		file_Broker_proto_pbBroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Broker_proto_pbBroker_proto_rawDesc), len(file_Broker_proto_pbBroker_proto_rawDesc)))
	})
	return file_Broker_proto_pbBroker_proto_rawDescData
}

var file_Broker_proto_pbBroker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Broker_proto_pbBroker_proto_goTypes = []any{
	(*Data)(nil),              // 0: pbBroker.Data
	(*Event)(nil),             // 1: pbBroker.Event
	(*Empty)(nil),             // 2: pbBroker.Empty
	(*IsAliveResponde)(nil),   // 3: pbBroker.IsAliveResponde
	(*HandshakeRequest)(nil),  // 4: pbBroker.HandshakeRequest
	(*HandshakeResponse)(nil), // 5: pbBroker.HandshakeResponse
}
var file_Broker_proto_pbBroker_proto_depIdxs = []int32{
	2, // 0: pbBroker.Broker.CheckIsAlive:input_type -> pbBroker.Empty
	4, // 1: pbBroker.Broker.Handshake:input_type -> pbBroker.HandshakeRequest
	3, // 2: pbBroker.Broker.CheckIsAlive:output_type -> pbBroker.IsAliveResponde
	5, // 3: pbBroker.Broker.Handshake:output_type -> pbBroker.HandshakeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Broker_proto_pbBroker_proto_init() }
func file_Broker_proto_pbBroker_proto_init() {
	if File_Broker_proto_pbBroker_proto != nil {
		return
	}
	file_Broker_proto_pbBroker_proto_msgTypes[4].OneofWrappers = []any{}
	file_Broker_proto_pbBroker_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Broker_proto_pbBroker_proto_rawDesc), len(file_Broker_proto_pbBroker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Broker_proto_pbBroker_proto_goTypes,
		DependencyIndexes: file_Broker_proto_pbBroker_proto_depIdxs,
		MessageInfos:      file_Broker_proto_pbBroker_proto_msgTypes,
	}.Build()
	File_Broker_proto_pbBroker_proto = out.File
	file_Broker_proto_pbBroker_proto_goTypes = nil
	file_Broker_proto_pbBroker_proto_depIdxs = nil
}
