// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: Banco/proto/pbBroker.proto

package pbBroker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_Banco_proto_pbBroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Banco_proto_pbBroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Banco_proto_pbBroker_proto_rawDescGZIP(), []int{0}
}

type IsAliveResponde struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAlive       bool                   `protobuf:"varint,1,opt,name=isAlive,proto3" json:"isAlive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAliveResponde) Reset() {
	*x = IsAliveResponde{}
	mi := &file_Banco_proto_pbBroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAliveResponde) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAliveResponde) ProtoMessage() {}

func (x *IsAliveResponde) ProtoReflect() protoreflect.Message {
	mi := &file_Banco_proto_pbBroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAliveResponde.ProtoReflect.Descriptor instead.
func (*IsAliveResponde) Descriptor() ([]byte, []int) {
	return file_Banco_proto_pbBroker_proto_rawDescGZIP(), []int{1}
}

func (x *IsAliveResponde) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	WhatIAm       string                 `protobuf:"bytes,2,opt,name=whatIAm,proto3" json:"whatIAm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_Banco_proto_pbBroker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Banco_proto_pbBroker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_Banco_proto_pbBroker_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *HandshakeRequest) GetWhatIAm() string {
	if x != nil {
		return x.WhatIAm
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_Banco_proto_pbBroker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Banco_proto_pbBroker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_Banco_proto_pbBroker_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_Banco_proto_pbBroker_proto protoreflect.FileDescriptor

const file_Banco_proto_pbBroker_proto_rawDesc = "" +
	"\n" +
	"\x1aBanco/proto/pbBroker.proto\x12\bpbBroker\"\a\n" +
	"\x05Empty\"+\n" +
	"\x0fIsAliveResponde\x12\x18\n" +
	"\aisAlive\x18\x01 \x01(\bR\aisAlive\"J\n" +
	"\x10HandshakeRequest\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x18\n" +
	"\awhatIAm\x18\x02 \x01(\tR\awhatIAm\"-\n" +
	"\x11HandshakeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8a\x01\n" +
	"\x06Broker\x12:\n" +
	"\fCheckIsAlive\x12\x0f.pbBroker.Empty\x1a\x19.pbBroker.IsAliveResponde\x12D\n" +
	"\tHandshake\x12\x1a.pbBroker.HandshakeRequest\x1a\x1b.pbBroker.HandshakeResponseB\fZ\n" +
	"./pbBrokerb\x06proto3"

var (
	file_Banco_proto_pbBroker_proto_rawDescOnce sync.Once
	file_Banco_proto_pbBroker_proto_rawDescData []byte
)

func file_Banco_proto_pbBroker_proto_rawDescGZIP() []byte {
	file_Banco_proto_pbBroker_proto_rawDescOnce.Do(func() {
		file_Banco_proto_pbBroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Banco_proto_pbBroker_proto_rawDesc), len(file_Banco_proto_pbBroker_proto_rawDesc)))
	})
	return file_Banco_proto_pbBroker_proto_rawDescData
}

var file_Banco_proto_pbBroker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Banco_proto_pbBroker_proto_goTypes = []any{
	(*Empty)(nil),             // 0: pbBroker.Empty
	(*IsAliveResponde)(nil),   // 1: pbBroker.IsAliveResponde
	(*HandshakeRequest)(nil),  // 2: pbBroker.HandshakeRequest
	(*HandshakeResponse)(nil), // 3: pbBroker.HandshakeResponse
}
var file_Banco_proto_pbBroker_proto_depIdxs = []int32{
	0, // 0: pbBroker.Broker.CheckIsAlive:input_type -> pbBroker.Empty
	2, // 1: pbBroker.Broker.Handshake:input_type -> pbBroker.HandshakeRequest
	1, // 2: pbBroker.Broker.CheckIsAlive:output_type -> pbBroker.IsAliveResponde
	3, // 3: pbBroker.Broker.Handshake:output_type -> pbBroker.HandshakeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Banco_proto_pbBroker_proto_init() }
func file_Banco_proto_pbBroker_proto_init() {
	if File_Banco_proto_pbBroker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Banco_proto_pbBroker_proto_rawDesc), len(file_Banco_proto_pbBroker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Banco_proto_pbBroker_proto_goTypes,
		DependencyIndexes: file_Banco_proto_pbBroker_proto_depIdxs,
		MessageInfos:      file_Banco_proto_pbBroker_proto_msgTypes,
	}.Build()
	File_Banco_proto_pbBroker_proto = out.File
	file_Banco_proto_pbBroker_proto_goTypes = nil
	file_Banco_proto_pbBroker_proto_depIdxs = nil
}
