syntax = "proto3";

option go_package = "./pbRegisterAuth";
package pbRegisterAuth;

// Service for Register and Authentication of Consumers, Productors
service RegisterAuth {
    // Register a new consumer o producer
    rpc Register (RegisterRequest) returns (RegisterResponse);
    
    // Authenticate an existing consumer o producer
    rpc Authenticate (AuthRequest) returns (AuthResponse);


    rpc RegisterNode (RegisterNodeRequest) returns (RegisterNodeResponse);
    rpc RegisterBanco (RegisterNodeRequest) returns (RegisterNodeResponse);
}

message RegisterRequest {
    string username = 1;
    string type = 2; // "consumer", "producer", "banco", "BD"
}

message RegisterResponse {
    string uuid = 1;
    bool success = 2;
    string message = 3;
}

message AuthRequest {
    string username = 1;
    string uuid = 2;
}

message AuthResponse {
    bool success = 1;
    string message = 2;
}

message RegisterNodeRequest {
    string uuid = 1;
    string direction = 2;
}

message RegisterNodeResponse {
    bool succes = 1;
    string message = 2;
}
