// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: server/proto/worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkCount     int32                  `protobuf:"varint,1,opt,name=work_count,json=workCount,proto3" json:"work_count,omitempty"`
	Data          int32                  `protobuf:"varint,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRequest) Reset() {
	*x = WorkerRequest{}
	mi := &file_server_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRequest) ProtoMessage() {}

func (x *WorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRequest.ProtoReflect.Descriptor instead.
func (*WorkerRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRequest) GetWorkCount() int32 {
	if x != nil {
		return x.WorkCount
	}
	return 0
}

func (x *WorkerRequest) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type WorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int32                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerResponse) Reset() {
	*x = WorkerResponse{}
	mi := &file_server_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResponse) ProtoMessage() {}

func (x *WorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResponse.ProtoReflect.Descriptor instead.
func (*WorkerResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerResponse) GetWorkerId() int32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *WorkerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_server_proto_worker_proto protoreflect.FileDescriptor

const file_server_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x19server/proto/worker.proto\x12\x06worker\"B\n" +
	"\rWorkerRequest\x12\x1d\n" +
	"\n" +
	"work_count\x18\x01 \x01(\x05R\tworkCount\x12\x12\n" +
	"\x04data\x18\x02 \x01(\x05R\x04data\"E\n" +
	"\x0eWorkerResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x05R\bworkerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06statusB\n" +
	"Z\b./workerb\x06proto3"

var (
	file_server_proto_worker_proto_rawDescOnce sync.Once
	file_server_proto_worker_proto_rawDescData []byte
)

func file_server_proto_worker_proto_rawDescGZIP() []byte {
	file_server_proto_worker_proto_rawDescOnce.Do(func() {
		file_server_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_worker_proto_rawDesc), len(file_server_proto_worker_proto_rawDesc)))
	})
	return file_server_proto_worker_proto_rawDescData
}

var file_server_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_proto_worker_proto_goTypes = []any{
	(*WorkerRequest)(nil),  // 0: worker.WorkerRequest
	(*WorkerResponse)(nil), // 1: worker.WorkerResponse
}
var file_server_proto_worker_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_proto_worker_proto_init() }
func file_server_proto_worker_proto_init() {
	if File_server_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_worker_proto_rawDesc), len(file_server_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_proto_worker_proto_goTypes,
		DependencyIndexes: file_server_proto_worker_proto_depIdxs,
		MessageInfos:      file_server_proto_worker_proto_msgTypes,
	}.Build()
	File_server_proto_worker_proto = out.File
	file_server_proto_worker_proto_goTypes = nil
	file_server_proto_worker_proto_depIdxs = nil
}
