// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: DynamoDB/proto/pbDynamoDB.proto

package pbDynamoDB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{0}
}

type IsAliveResponde struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAlive       bool                   `protobuf:"varint,1,opt,name=isAlive,proto3" json:"isAlive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAliveResponde) Reset() {
	*x = IsAliveResponde{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAliveResponde) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAliveResponde) ProtoMessage() {}

func (x *IsAliveResponde) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAliveResponde.ProtoReflect.Descriptor instead.
func (*IsAliveResponde) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{1}
}

func (x *IsAliveResponde) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

var File_DynamoDB_proto_pbDynamoDB_proto protoreflect.FileDescriptor

const file_DynamoDB_proto_pbDynamoDB_proto_rawDesc = "" +
	"\n" +
	"\x1fDynamoDB/proto/pbDynamoDB.proto\x12\n" +
	"pbDynamoDB\"\a\n" +
	"\x05Empty\"+\n" +
	"\x0fIsAliveResponde\x12\x18\n" +
	"\aisAlive\x18\x01 \x01(\bR\aisAlive2J\n" +
	"\bDynamoDB\x12>\n" +
	"\fCheckIsAlive\x12\x11.pbDynamoDB.Empty\x1a\x1b.pbDynamoDB.IsAliveRespondeB\x0eZ\f./pbDynamoDBb\x06proto3"

var (
	file_DynamoDB_proto_pbDynamoDB_proto_rawDescOnce sync.Once
	file_DynamoDB_proto_pbDynamoDB_proto_rawDescData []byte
)

func file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP() []byte {
	file_DynamoDB_proto_pbDynamoDB_proto_rawDescOnce.Do(func() {
		file_DynamoDB_proto_pbDynamoDB_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DynamoDB_proto_pbDynamoDB_proto_rawDesc), len(file_DynamoDB_proto_pbDynamoDB_proto_rawDesc)))
	})
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescData
}

var file_DynamoDB_proto_pbDynamoDB_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_DynamoDB_proto_pbDynamoDB_proto_goTypes = []any{
	(*Empty)(nil),           // 0: pbDynamoDB.Empty
	(*IsAliveResponde)(nil), // 1: pbDynamoDB.IsAliveResponde
}
var file_DynamoDB_proto_pbDynamoDB_proto_depIdxs = []int32{
	0, // 0: pbDynamoDB.DynamoDB.CheckIsAlive:input_type -> pbDynamoDB.Empty
	1, // 1: pbDynamoDB.DynamoDB.CheckIsAlive:output_type -> pbDynamoDB.IsAliveResponde
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DynamoDB_proto_pbDynamoDB_proto_init() }
func file_DynamoDB_proto_pbDynamoDB_proto_init() {
	if File_DynamoDB_proto_pbDynamoDB_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DynamoDB_proto_pbDynamoDB_proto_rawDesc), len(file_DynamoDB_proto_pbDynamoDB_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_DynamoDB_proto_pbDynamoDB_proto_goTypes,
		DependencyIndexes: file_DynamoDB_proto_pbDynamoDB_proto_depIdxs,
		MessageInfos:      file_DynamoDB_proto_pbDynamoDB_proto_msgTypes,
	}.Build()
	File_DynamoDB_proto_pbDynamoDB_proto = out.File
	file_DynamoDB_proto_pbDynamoDB_proto_goTypes = nil
	file_DynamoDB_proto_pbDynamoDB_proto_depIdxs = nil
}
