// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: DynamoDB/proto/pbDynamoDB.proto

package pbDynamoDB

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DynamoDB_CheckIsAlive_FullMethodName = "/pbDynamoDB.DynamoDB/CheckIsAlive"
)

// DynamoDBClient is the client API for DynamoDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for Register and Authentication of Consumers, Productors
type DynamoDBClient interface {
	CheckIsAlive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IsAliveResponde, error)
}

type dynamoDBClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamoDBClient(cc grpc.ClientConnInterface) DynamoDBClient {
	return &dynamoDBClient{cc}
}

func (c *dynamoDBClient) CheckIsAlive(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IsAliveResponde, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAliveResponde)
	err := c.cc.Invoke(ctx, DynamoDB_CheckIsAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamoDBServer is the server API for DynamoDB service.
// All implementations must embed UnimplementedDynamoDBServer
// for forward compatibility.
//
// Service for Register and Authentication of Consumers, Productors
type DynamoDBServer interface {
	CheckIsAlive(context.Context, *Empty) (*IsAliveResponde, error)
	mustEmbedUnimplementedDynamoDBServer()
}

// UnimplementedDynamoDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynamoDBServer struct{}

func (UnimplementedDynamoDBServer) CheckIsAlive(context.Context, *Empty) (*IsAliveResponde, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIsAlive not implemented")
}
func (UnimplementedDynamoDBServer) mustEmbedUnimplementedDynamoDBServer() {}
func (UnimplementedDynamoDBServer) testEmbeddedByValue()                  {}

// UnsafeDynamoDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamoDBServer will
// result in compilation errors.
type UnsafeDynamoDBServer interface {
	mustEmbedUnimplementedDynamoDBServer()
}

func RegisterDynamoDBServer(s grpc.ServiceRegistrar, srv DynamoDBServer) {
	// If the following call panics, it indicates UnimplementedDynamoDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DynamoDB_ServiceDesc, srv)
}

func _DynamoDB_CheckIsAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamoDBServer).CheckIsAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamoDB_CheckIsAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamoDBServer).CheckIsAlive(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DynamoDB_ServiceDesc is the grpc.ServiceDesc for DynamoDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynamoDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbDynamoDB.DynamoDB",
	HandlerType: (*DynamoDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIsAlive",
			Handler:    _DynamoDB_CheckIsAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "DynamoDB/proto/pbDynamoDB.proto",
}
