// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: DynamoDB/proto/pbDynamoDB.proto

package pbDynamoDB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{0}
}

type IsAliveResponde struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAlive       bool                   `protobuf:"varint,1,opt,name=isAlive,proto3" json:"isAlive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAliveResponde) Reset() {
	*x = IsAliveResponde{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAliveResponde) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAliveResponde) ProtoMessage() {}

func (x *IsAliveResponde) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAliveResponde.ProtoReflect.Descriptor instead.
func (*IsAliveResponde) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{1}
}

func (x *IsAliveResponde) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

type CreateTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTableRequest) Reset() {
	*x = CreateTableRequest{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableRequest) ProtoMessage() {}

func (x *CreateTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableRequest.ProtoReflect.Descriptor instead.
func (*CreateTableRequest) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTableRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type CreateTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTableResponse) Reset() {
	*x = CreateTableResponse{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableResponse) ProtoMessage() {}

func (x *CreateTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableResponse.ProtoReflect.Descriptor instead.
func (*CreateTableResponse) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTableResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PutItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutItemRequest) Reset() {
	*x = PutItemRequest{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutItemRequest) ProtoMessage() {}

func (x *PutItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutItemRequest.ProtoReflect.Descriptor instead.
func (*PutItemRequest) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{4}
}

func (x *PutItemRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *PutItemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutItemRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutItemResponse) Reset() {
	*x = PutItemResponse{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutItemResponse) ProtoMessage() {}

func (x *PutItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutItemResponse.ProtoReflect.Descriptor instead.
func (*PutItemResponse) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{5}
}

func (x *PutItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{6}
}

func (x *GetItemRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetItemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{7}
}

func (x *Item) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Item) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value         *Item                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{8}
}

func (x *GetItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetItemResponse) GetValue() *Item {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Table struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          map[string][]byte      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{9}
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetData() map[string][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SyncAllDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllData       []*Table               `protobuf:"bytes,1,rep,name=allData,proto3" json:"allData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAllDataRequest) Reset() {
	*x = SyncAllDataRequest{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllDataRequest) ProtoMessage() {}

func (x *SyncAllDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllDataRequest.ProtoReflect.Descriptor instead.
func (*SyncAllDataRequest) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{10}
}

func (x *SyncAllDataRequest) GetAllData() []*Table {
	if x != nil {
		return x.AllData
	}
	return nil
}

type SyncAllDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAllDataResponse) Reset() {
	*x = SyncAllDataResponse{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllDataResponse) ProtoMessage() {}

func (x *SyncAllDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllDataResponse.ProtoReflect.Descriptor instead.
func (*SyncAllDataResponse) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{11}
}

func (x *SyncAllDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncAllDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AllData       []*Table               `protobuf:"bytes,2,rep,name=allData,proto3" json:"allData,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDataResponse) Reset() {
	*x = GetAllDataResponse{}
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDataResponse) ProtoMessage() {}

func (x *GetAllDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_DynamoDB_proto_pbDynamoDB_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDataResponse.ProtoReflect.Descriptor instead.
func (*GetAllDataResponse) Descriptor() ([]byte, []int) {
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllDataResponse) GetAllData() []*Table {
	if x != nil {
		return x.AllData
	}
	return nil
}

func (x *GetAllDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_DynamoDB_proto_pbDynamoDB_proto protoreflect.FileDescriptor

const file_DynamoDB_proto_pbDynamoDB_proto_rawDesc = "" +
	"\n" +
	"\x1fDynamoDB/proto/pbDynamoDB.proto\x12\n" +
	"pbDynamoDB\"\a\n" +
	"\x05Empty\"+\n" +
	"\x0fIsAliveResponde\x12\x18\n" +
	"\aisAlive\x18\x01 \x01(\bR\aisAlive\"3\n" +
	"\x12CreateTableRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\"I\n" +
	"\x13CreateTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x0ePutItemRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"E\n" +
	"\x0fPutItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x0eGetItemRequest\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"4\n" +
	"\x04Item\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"m\n" +
	"\x0fGetItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.pbDynamoDB.ItemR\x05value\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x85\x01\n" +
	"\x05Table\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x04data\x18\x02 \x03(\v2\x1b.pbDynamoDB.Table.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"A\n" +
	"\x12SyncAllDataRequest\x12+\n" +
	"\aallData\x18\x01 \x03(\v2\x11.pbDynamoDB.TableR\aallData\"I\n" +
	"\x13SyncAllDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"u\n" +
	"\x12GetAllDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\aallData\x18\x02 \x03(\v2\x11.pbDynamoDB.TableR\aallData\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xb3\x03\n" +
	"\bDynamoDB\x12>\n" +
	"\fCheckIsAlive\x12\x11.pbDynamoDB.Empty\x1a\x1b.pbDynamoDB.IsAliveResponde\x12N\n" +
	"\vCreateTable\x12\x1e.pbDynamoDB.CreateTableRequest\x1a\x1f.pbDynamoDB.CreateTableResponse\x12B\n" +
	"\aPutItem\x12\x1a.pbDynamoDB.PutItemRequest\x1a\x1b.pbDynamoDB.PutItemResponse\x12B\n" +
	"\aGetItem\x12\x1a.pbDynamoDB.GetItemRequest\x1a\x1b.pbDynamoDB.GetItemResponse\x12N\n" +
	"\vSyncAllData\x12\x1e.pbDynamoDB.SyncAllDataRequest\x1a\x1f.pbDynamoDB.SyncAllDataResponse\x12?\n" +
	"\n" +
	"GetAllData\x12\x11.pbDynamoDB.Empty\x1a\x1e.pbDynamoDB.GetAllDataResponseB\x0eZ\f./pbDynamoDBb\x06proto3"

var (
	file_DynamoDB_proto_pbDynamoDB_proto_rawDescOnce sync.Once
	file_DynamoDB_proto_pbDynamoDB_proto_rawDescData []byte
)

func file_DynamoDB_proto_pbDynamoDB_proto_rawDescGZIP() []byte {
	file_DynamoDB_proto_pbDynamoDB_proto_rawDescOnce.Do(func() {
		file_DynamoDB_proto_pbDynamoDB_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DynamoDB_proto_pbDynamoDB_proto_rawDesc), len(file_DynamoDB_proto_pbDynamoDB_proto_rawDesc)))
	})
	return file_DynamoDB_proto_pbDynamoDB_proto_rawDescData
}

var file_DynamoDB_proto_pbDynamoDB_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_DynamoDB_proto_pbDynamoDB_proto_goTypes = []any{
	(*Empty)(nil),               // 0: pbDynamoDB.Empty
	(*IsAliveResponde)(nil),     // 1: pbDynamoDB.IsAliveResponde
	(*CreateTableRequest)(nil),  // 2: pbDynamoDB.CreateTableRequest
	(*CreateTableResponse)(nil), // 3: pbDynamoDB.CreateTableResponse
	(*PutItemRequest)(nil),      // 4: pbDynamoDB.PutItemRequest
	(*PutItemResponse)(nil),     // 5: pbDynamoDB.PutItemResponse
	(*GetItemRequest)(nil),      // 6: pbDynamoDB.GetItemRequest
	(*Item)(nil),                // 7: pbDynamoDB.Item
	(*GetItemResponse)(nil),     // 8: pbDynamoDB.GetItemResponse
	(*Table)(nil),               // 9: pbDynamoDB.Table
	(*SyncAllDataRequest)(nil),  // 10: pbDynamoDB.SyncAllDataRequest
	(*SyncAllDataResponse)(nil), // 11: pbDynamoDB.SyncAllDataResponse
	(*GetAllDataResponse)(nil),  // 12: pbDynamoDB.GetAllDataResponse
	nil,                         // 13: pbDynamoDB.Table.DataEntry
}
var file_DynamoDB_proto_pbDynamoDB_proto_depIdxs = []int32{
	7,  // 0: pbDynamoDB.GetItemResponse.value:type_name -> pbDynamoDB.Item
	13, // 1: pbDynamoDB.Table.data:type_name -> pbDynamoDB.Table.DataEntry
	9,  // 2: pbDynamoDB.SyncAllDataRequest.allData:type_name -> pbDynamoDB.Table
	9,  // 3: pbDynamoDB.GetAllDataResponse.allData:type_name -> pbDynamoDB.Table
	0,  // 4: pbDynamoDB.DynamoDB.CheckIsAlive:input_type -> pbDynamoDB.Empty
	2,  // 5: pbDynamoDB.DynamoDB.CreateTable:input_type -> pbDynamoDB.CreateTableRequest
	4,  // 6: pbDynamoDB.DynamoDB.PutItem:input_type -> pbDynamoDB.PutItemRequest
	6,  // 7: pbDynamoDB.DynamoDB.GetItem:input_type -> pbDynamoDB.GetItemRequest
	10, // 8: pbDynamoDB.DynamoDB.SyncAllData:input_type -> pbDynamoDB.SyncAllDataRequest
	0,  // 9: pbDynamoDB.DynamoDB.GetAllData:input_type -> pbDynamoDB.Empty
	1,  // 10: pbDynamoDB.DynamoDB.CheckIsAlive:output_type -> pbDynamoDB.IsAliveResponde
	3,  // 11: pbDynamoDB.DynamoDB.CreateTable:output_type -> pbDynamoDB.CreateTableResponse
	5,  // 12: pbDynamoDB.DynamoDB.PutItem:output_type -> pbDynamoDB.PutItemResponse
	8,  // 13: pbDynamoDB.DynamoDB.GetItem:output_type -> pbDynamoDB.GetItemResponse
	11, // 14: pbDynamoDB.DynamoDB.SyncAllData:output_type -> pbDynamoDB.SyncAllDataResponse
	12, // 15: pbDynamoDB.DynamoDB.GetAllData:output_type -> pbDynamoDB.GetAllDataResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_DynamoDB_proto_pbDynamoDB_proto_init() }
func file_DynamoDB_proto_pbDynamoDB_proto_init() {
	if File_DynamoDB_proto_pbDynamoDB_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DynamoDB_proto_pbDynamoDB_proto_rawDesc), len(file_DynamoDB_proto_pbDynamoDB_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_DynamoDB_proto_pbDynamoDB_proto_goTypes,
		DependencyIndexes: file_DynamoDB_proto_pbDynamoDB_proto_depIdxs,
		MessageInfos:      file_DynamoDB_proto_pbDynamoDB_proto_msgTypes,
	}.Build()
	File_DynamoDB_proto_pbDynamoDB_proto = out.File
	file_DynamoDB_proto_pbDynamoDB_proto_goTypes = nil
	file_DynamoDB_proto_pbDynamoDB_proto_depIdxs = nil
}
