// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: Broker/proto/pbRegisterAuth.proto

package pbRegisterAuth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegisterAuth_Register_FullMethodName      = "/pbRegisterAuth.RegisterAuth/Register"
	RegisterAuth_Authenticate_FullMethodName  = "/pbRegisterAuth.RegisterAuth/Authenticate"
	RegisterAuth_RegisterNode_FullMethodName  = "/pbRegisterAuth.RegisterAuth/RegisterNode"
	RegisterAuth_RegisterBanco_FullMethodName = "/pbRegisterAuth.RegisterAuth/RegisterBanco"
)

// RegisterAuthClient is the client API for RegisterAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for Register and Authentication of Consumers, Productors
type RegisterAuthClient interface {
	// Register a new consumer o producer
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Authenticate an existing consumer o producer
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	RegisterBanco(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
}

type registerAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterAuthClient(cc grpc.ClientConnInterface) RegisterAuthClient {
	return &registerAuthClient{cc}
}

func (c *registerAuthClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, RegisterAuth_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerAuthClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, RegisterAuth_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerAuthClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, RegisterAuth_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerAuthClient) RegisterBanco(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, RegisterAuth_RegisterBanco_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterAuthServer is the server API for RegisterAuth service.
// All implementations must embed UnimplementedRegisterAuthServer
// for forward compatibility.
//
// Service for Register and Authentication of Consumers, Productors
type RegisterAuthServer interface {
	// Register a new consumer o producer
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Authenticate an existing consumer o producer
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	RegisterBanco(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	mustEmbedUnimplementedRegisterAuthServer()
}

// UnimplementedRegisterAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegisterAuthServer struct{}

func (UnimplementedRegisterAuthServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegisterAuthServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedRegisterAuthServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedRegisterAuthServer) RegisterBanco(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBanco not implemented")
}
func (UnimplementedRegisterAuthServer) mustEmbedUnimplementedRegisterAuthServer() {}
func (UnimplementedRegisterAuthServer) testEmbeddedByValue()                      {}

// UnsafeRegisterAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterAuthServer will
// result in compilation errors.
type UnsafeRegisterAuthServer interface {
	mustEmbedUnimplementedRegisterAuthServer()
}

func RegisterRegisterAuthServer(s grpc.ServiceRegistrar, srv RegisterAuthServer) {
	// If the following call panics, it indicates UnimplementedRegisterAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegisterAuth_ServiceDesc, srv)
}

func _RegisterAuth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterAuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterAuth_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterAuthServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegisterAuth_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterAuthServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterAuth_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterAuthServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegisterAuth_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterAuthServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterAuth_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterAuthServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegisterAuth_RegisterBanco_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterAuthServer).RegisterBanco(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterAuth_RegisterBanco_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterAuthServer).RegisterBanco(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterAuth_ServiceDesc is the grpc.ServiceDesc for RegisterAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbRegisterAuth.RegisterAuth",
	HandlerType: (*RegisterAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RegisterAuth_Register_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _RegisterAuth_Authenticate_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _RegisterAuth_RegisterNode_Handler,
		},
		{
			MethodName: "RegisterBanco",
			Handler:    _RegisterAuth_RegisterBanco_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Broker/proto/pbRegisterAuth.proto",
}
