// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: Broker/proto/pbConsumer.proto

package pbConsumer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventsRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Event struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventID          string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	Discoteca        string                 `protobuf:"bytes,2,opt,name=discoteca,proto3" json:"discoteca,omitempty"`
	NombreEvento     string                 `protobuf:"bytes,3,opt,name=nombreEvento,proto3" json:"nombreEvento,omitempty"`
	Categoria        string                 `protobuf:"bytes,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Comuna           string                 `protobuf:"bytes,5,opt,name=comuna,proto3" json:"comuna,omitempty"`
	Precio           int32                  `protobuf:"varint,6,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock            int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	SpendStock       int32                  `protobuf:"varint,8,opt,name=spendStock,proto3" json:"spendStock,omitempty"`
	FechaEvento      string                 `protobuf:"bytes,9,opt,name=fechaEvento,proto3" json:"fechaEvento,omitempty"`
	FechaPublicacion string                 `protobuf:"bytes,10,opt,name=fechaPublicacion,proto3" json:"fechaPublicacion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *Event) GetDiscoteca() string {
	if x != nil {
		return x.Discoteca
	}
	return ""
}

func (x *Event) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *Event) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Event) GetComuna() string {
	if x != nil {
		return x.Comuna
	}
	return ""
}

func (x *Event) GetPrecio() int32 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Event) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Event) GetSpendStock() int32 {
	if x != nil {
		return x.SpendStock
	}
	return 0
}

func (x *Event) GetFechaEvento() string {
	if x != nil {
		return x.FechaEvento
	}
	return ""
}

func (x *Event) GetFechaPublicacion() string {
	if x != nil {
		return x.FechaPublicacion
	}
	return ""
}

type PurchaseEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	EventID       string                 `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	TicketID      string                 `protobuf:"bytes,3,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	FechaEvento   string                 `protobuf:"bytes,5,opt,name=fechaEvento,proto3" json:"fechaEvento,omitempty"`
	FechaCompra   string                 `protobuf:"bytes,6,opt,name=fechaCompra,proto3" json:"fechaCompra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseEntry) Reset() {
	*x = PurchaseEntry{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseEntry) ProtoMessage() {}

func (x *PurchaseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseEntry.ProtoReflect.Descriptor instead.
func (*PurchaseEntry) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{2}
}

func (x *PurchaseEntry) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *PurchaseEntry) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *PurchaseEntry) GetTicketID() string {
	if x != nil {
		return x.TicketID
	}
	return ""
}

func (x *PurchaseEntry) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PurchaseEntry) GetFechaEvento() string {
	if x != nil {
		return x.FechaEvento
	}
	return ""
}

func (x *PurchaseEntry) GetFechaCompra() string {
	if x != nil {
		return x.FechaCompra
	}
	return ""
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEventsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type PurchaseEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventID       string                 `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"` // e.g. "debito", "credito"
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseEventRequest) Reset() {
	*x = PurchaseEventRequest{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseEventRequest) ProtoMessage() {}

func (x *PurchaseEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseEventRequest.ProtoReflect.Descriptor instead.
func (*PurchaseEventRequest) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{4}
}

func (x *PurchaseEventRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PurchaseEventRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *PurchaseEventRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PurchaseEventRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PurchaseEventResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PurchaseResult *PurchaseEntry         `protobuf:"bytes,3,opt,name=purchaseResult,proto3" json:"purchaseResult,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PurchaseEventResponse) Reset() {
	*x = PurchaseEventResponse{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseEventResponse) ProtoMessage() {}

func (x *PurchaseEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseEventResponse.ProtoReflect.Descriptor instead.
func (*PurchaseEventResponse) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{5}
}

func (x *PurchaseEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PurchaseEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PurchaseEventResponse) GetPurchaseResult() *PurchaseEntry {
	if x != nil {
		return x.PurchaseResult
	}
	return nil
}

var File_Broker_proto_pbConsumer_proto protoreflect.FileDescriptor

const file_Broker_proto_pbConsumer_proto_rawDesc = "" +
	"\n" +
	"\x1dBroker/proto/pbConsumer.proto\x12\n" +
	"pbConsumer\"&\n" +
	"\x10GetEventsRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xb5\x02\n" +
	"\x05Event\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12\x1c\n" +
	"\tdiscoteca\x18\x02 \x01(\tR\tdiscoteca\x12\"\n" +
	"\fnombreEvento\x18\x03 \x01(\tR\fnombreEvento\x12\x1c\n" +
	"\tcategoria\x18\x04 \x01(\tR\tcategoria\x12\x16\n" +
	"\x06comuna\x18\x05 \x01(\tR\x06comuna\x12\x16\n" +
	"\x06precio\x18\x06 \x01(\x05R\x06precio\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1e\n" +
	"\n" +
	"spendStock\x18\b \x01(\x05R\n" +
	"spendStock\x12 \n" +
	"\vfechaEvento\x18\t \x01(\tR\vfechaEvento\x12*\n" +
	"\x10fechaPublicacion\x18\n" +
	" \x01(\tR\x10fechaPublicacion\"\xc3\x01\n" +
	"\rPurchaseEntry\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x18\n" +
	"\aeventID\x18\x02 \x01(\tR\aeventID\x12\x1a\n" +
	"\bticketID\x18\x03 \x01(\tR\bticketID\x12$\n" +
	"\rpaymentMethod\x18\x04 \x01(\tR\rpaymentMethod\x12 \n" +
	"\vfechaEvento\x18\x05 \x01(\tR\vfechaEvento\x12 \n" +
	"\vfechaCompra\x18\x06 \x01(\tR\vfechaCompra\"r\n" +
	"\x11GetEventsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x06events\x18\x03 \x03(\v2\x11.pbConsumer.EventR\x06events\"\x86\x01\n" +
	"\x14PurchaseEventRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\aeventID\x18\x02 \x01(\tR\aeventID\x12$\n" +
	"\rpaymentMethod\x18\x03 \x01(\tR\rpaymentMethod\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"\x8e\x01\n" +
	"\x15PurchaseEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\x0epurchaseResult\x18\x03 \x01(\v2\x19.pbConsumer.PurchaseEntryR\x0epurchaseResult2\xaa\x01\n" +
	"\bConsumer\x12H\n" +
	"\tGetEvents\x12\x1c.pbConsumer.GetEventsRequest\x1a\x1d.pbConsumer.GetEventsResponse\x12T\n" +
	"\rPurchaseEvent\x12 .pbConsumer.PurchaseEventRequest\x1a!.pbConsumer.PurchaseEventResponseB\x0eZ\f./pbConsumerb\x06proto3"

var (
	file_Broker_proto_pbConsumer_proto_rawDescOnce sync.Once
	file_Broker_proto_pbConsumer_proto_rawDescData []byte
)

func file_Broker_proto_pbConsumer_proto_rawDescGZIP() []byte {
	file_Broker_proto_pbConsumer_proto_rawDescOnce.Do(func() {
		file_Broker_proto_pbConsumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Broker_proto_pbConsumer_proto_rawDesc), len(file_Broker_proto_pbConsumer_proto_rawDesc)))
	})
	return file_Broker_proto_pbConsumer_proto_rawDescData
}

var file_Broker_proto_pbConsumer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Broker_proto_pbConsumer_proto_goTypes = []any{
	(*GetEventsRequest)(nil),      // 0: pbConsumer.GetEventsRequest
	(*Event)(nil),                 // 1: pbConsumer.Event
	(*PurchaseEntry)(nil),         // 2: pbConsumer.PurchaseEntry
	(*GetEventsResponse)(nil),     // 3: pbConsumer.GetEventsResponse
	(*PurchaseEventRequest)(nil),  // 4: pbConsumer.PurchaseEventRequest
	(*PurchaseEventResponse)(nil), // 5: pbConsumer.PurchaseEventResponse
}
var file_Broker_proto_pbConsumer_proto_depIdxs = []int32{
	1, // 0: pbConsumer.GetEventsResponse.events:type_name -> pbConsumer.Event
	2, // 1: pbConsumer.PurchaseEventResponse.purchaseResult:type_name -> pbConsumer.PurchaseEntry
	0, // 2: pbConsumer.Consumer.GetEvents:input_type -> pbConsumer.GetEventsRequest
	4, // 3: pbConsumer.Consumer.PurchaseEvent:input_type -> pbConsumer.PurchaseEventRequest
	3, // 4: pbConsumer.Consumer.GetEvents:output_type -> pbConsumer.GetEventsResponse
	5, // 5: pbConsumer.Consumer.PurchaseEvent:output_type -> pbConsumer.PurchaseEventResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Broker_proto_pbConsumer_proto_init() }
func file_Broker_proto_pbConsumer_proto_init() {
	if File_Broker_proto_pbConsumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Broker_proto_pbConsumer_proto_rawDesc), len(file_Broker_proto_pbConsumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Broker_proto_pbConsumer_proto_goTypes,
		DependencyIndexes: file_Broker_proto_pbConsumer_proto_depIdxs,
		MessageInfos:      file_Broker_proto_pbConsumer_proto_msgTypes,
	}.Build()
	File_Broker_proto_pbConsumer_proto = out.File
	file_Broker_proto_pbConsumer_proto_goTypes = nil
	file_Broker_proto_pbConsumer_proto_depIdxs = nil
}
