// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: Broker/proto/pbConsumer.proto

package pbConsumer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventsRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventID       string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	Discoteca     string                 `protobuf:"bytes,2,opt,name=discoteca,proto3" json:"discoteca,omitempty"`
	NombreEvento  string                 `protobuf:"bytes,3,opt,name=nombreEvento,proto3" json:"nombreEvento,omitempty"`
	Categoria     string                 `protobuf:"bytes,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
	Comuna        string                 `protobuf:"bytes,5,opt,name=comuna,proto3" json:"comuna,omitempty"`
	Precio        int32                  `protobuf:"varint,6,opt,name=precio,proto3" json:"precio,omitempty"`
	Stock         int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	FechaEvento   string                 `protobuf:"bytes,8,opt,name=fechaEvento,proto3" json:"fechaEvento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{1}
}

func (x *Events) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *Events) GetDiscoteca() string {
	if x != nil {
		return x.Discoteca
	}
	return ""
}

func (x *Events) GetNombreEvento() string {
	if x != nil {
		return x.NombreEvento
	}
	return ""
}

func (x *Events) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

func (x *Events) GetComuna() string {
	if x != nil {
		return x.Comuna
	}
	return ""
}

func (x *Events) GetPrecio() int32 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Events) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Events) GetFechaEvento() string {
	if x != nil {
		return x.FechaEvento
	}
	return ""
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succes        bool                   `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Events        []*Events              `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventsResponse) GetSucces() bool {
	if x != nil {
		return x.Succes
	}
	return false
}

func (x *GetEventsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEventsResponse) GetEvents() []*Events {
	if x != nil {
		return x.Events
	}
	return nil
}

type PurchaseEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EventID       string                 `protobuf:"bytes,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"` // e.g. "debito", "credito"
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseEventRequest) Reset() {
	*x = PurchaseEventRequest{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseEventRequest) ProtoMessage() {}

func (x *PurchaseEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseEventRequest.ProtoReflect.Descriptor instead.
func (*PurchaseEventRequest) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{3}
}

func (x *PurchaseEventRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PurchaseEventRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *PurchaseEventRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PurchaseEventRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PurchaseEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succes        bool                   `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TicketID      string                 `protobuf:"bytes,3,opt,name=ticketID,proto3" json:"ticketID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseEventResponse) Reset() {
	*x = PurchaseEventResponse{}
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseEventResponse) ProtoMessage() {}

func (x *PurchaseEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Broker_proto_pbConsumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseEventResponse.ProtoReflect.Descriptor instead.
func (*PurchaseEventResponse) Descriptor() ([]byte, []int) {
	return file_Broker_proto_pbConsumer_proto_rawDescGZIP(), []int{4}
}

func (x *PurchaseEventResponse) GetSucces() bool {
	if x != nil {
		return x.Succes
	}
	return false
}

func (x *PurchaseEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PurchaseEventResponse) GetTicketID() string {
	if x != nil {
		return x.TicketID
	}
	return ""
}

var File_Broker_proto_pbConsumer_proto protoreflect.FileDescriptor

const file_Broker_proto_pbConsumer_proto_rawDesc = "" +
	"\n" +
	"\x1dBroker/proto/pbConsumer.proto\x12\n" +
	"pbConsumer\"&\n" +
	"\x10GetEventsRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xea\x01\n" +
	"\x06Events\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12\x1c\n" +
	"\tdiscoteca\x18\x02 \x01(\tR\tdiscoteca\x12\"\n" +
	"\fnombreEvento\x18\x03 \x01(\tR\fnombreEvento\x12\x1c\n" +
	"\tcategoria\x18\x04 \x01(\tR\tcategoria\x12\x16\n" +
	"\x06comuna\x18\x05 \x01(\tR\x06comuna\x12\x16\n" +
	"\x06precio\x18\x06 \x01(\x05R\x06precio\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12 \n" +
	"\vfechaEvento\x18\b \x01(\tR\vfechaEvento\"q\n" +
	"\x11GetEventsResponse\x12\x16\n" +
	"\x06succes\x18\x01 \x01(\bR\x06succes\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x06events\x18\x03 \x03(\v2\x12.pbConsumer.EventsR\x06events\"\x86\x01\n" +
	"\x14PurchaseEventRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\aeventID\x18\x02 \x01(\tR\aeventID\x12$\n" +
	"\rpaymentMethod\x18\x03 \x01(\tR\rpaymentMethod\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"e\n" +
	"\x15PurchaseEventResponse\x12\x16\n" +
	"\x06succes\x18\x01 \x01(\bR\x06succes\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bticketID\x18\x03 \x01(\tR\bticketID2\xaa\x01\n" +
	"\bConsumer\x12H\n" +
	"\tGetEvents\x12\x1c.pbConsumer.GetEventsRequest\x1a\x1d.pbConsumer.GetEventsResponse\x12T\n" +
	"\rPurchaseEvent\x12 .pbConsumer.PurchaseEventRequest\x1a!.pbConsumer.PurchaseEventResponseB\x0eZ\f./pbConsumerb\x06proto3"

var (
	file_Broker_proto_pbConsumer_proto_rawDescOnce sync.Once
	file_Broker_proto_pbConsumer_proto_rawDescData []byte
)

func file_Broker_proto_pbConsumer_proto_rawDescGZIP() []byte {
	file_Broker_proto_pbConsumer_proto_rawDescOnce.Do(func() {
		file_Broker_proto_pbConsumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Broker_proto_pbConsumer_proto_rawDesc), len(file_Broker_proto_pbConsumer_proto_rawDesc)))
	})
	return file_Broker_proto_pbConsumer_proto_rawDescData
}

var file_Broker_proto_pbConsumer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Broker_proto_pbConsumer_proto_goTypes = []any{
	(*GetEventsRequest)(nil),      // 0: pbConsumer.GetEventsRequest
	(*Events)(nil),                // 1: pbConsumer.Events
	(*GetEventsResponse)(nil),     // 2: pbConsumer.GetEventsResponse
	(*PurchaseEventRequest)(nil),  // 3: pbConsumer.PurchaseEventRequest
	(*PurchaseEventResponse)(nil), // 4: pbConsumer.PurchaseEventResponse
}
var file_Broker_proto_pbConsumer_proto_depIdxs = []int32{
	1, // 0: pbConsumer.GetEventsResponse.events:type_name -> pbConsumer.Events
	0, // 1: pbConsumer.Consumer.GetEvents:input_type -> pbConsumer.GetEventsRequest
	3, // 2: pbConsumer.Consumer.PurchaseEvent:input_type -> pbConsumer.PurchaseEventRequest
	2, // 3: pbConsumer.Consumer.GetEvents:output_type -> pbConsumer.GetEventsResponse
	4, // 4: pbConsumer.Consumer.PurchaseEvent:output_type -> pbConsumer.PurchaseEventResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Broker_proto_pbConsumer_proto_init() }
func file_Broker_proto_pbConsumer_proto_init() {
	if File_Broker_proto_pbConsumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Broker_proto_pbConsumer_proto_rawDesc), len(file_Broker_proto_pbConsumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Broker_proto_pbConsumer_proto_goTypes,
		DependencyIndexes: file_Broker_proto_pbConsumer_proto_depIdxs,
		MessageInfos:      file_Broker_proto_pbConsumer_proto_msgTypes,
	}.Build()
	File_Broker_proto_pbConsumer_proto = out.File
	file_Broker_proto_pbConsumer_proto_goTypes = nil
	file_Broker_proto_pbConsumer_proto_depIdxs = nil
}
