// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: client/proto/server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	TaskData      int32                  `protobuf:"varint,2,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRequest) Reset() {
	*x = ServerRequest{}
	mi := &file_client_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest) ProtoMessage() {}

func (x *ServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest.ProtoReflect.Descriptor instead.
func (*ServerRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ServerRequest) GetTaskData() int32 {
	if x != nil {
		return x.TaskData
	}
	return 0
}

type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_client_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_client_proto_server_proto protoreflect.FileDescriptor

const file_client_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x19client/proto/server.proto\x12\x06server\"I\n" +
	"\rServerRequest\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12\x1b\n" +
	"\ttask_data\x18\x02 \x01(\x05R\btaskData\"(\n" +
	"\x0eServerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2H\n" +
	"\rServerService\x127\n" +
	"\x06Submit\x12\x15.server.ServerRequest\x1a\x16.server.ServerResponseB\n" +
	"Z\b./serverb\x06proto3"

var (
	file_client_proto_server_proto_rawDescOnce sync.Once
	file_client_proto_server_proto_rawDescData []byte
)

func file_client_proto_server_proto_rawDescGZIP() []byte {
	file_client_proto_server_proto_rawDescOnce.Do(func() {
		file_client_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_server_proto_rawDesc), len(file_client_proto_server_proto_rawDesc)))
	})
	return file_client_proto_server_proto_rawDescData
}

var file_client_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_proto_server_proto_goTypes = []any{
	(*ServerRequest)(nil),  // 0: server.ServerRequest
	(*ServerResponse)(nil), // 1: server.ServerResponse
}
var file_client_proto_server_proto_depIdxs = []int32{
	0, // 0: server.ServerService.Submit:input_type -> server.ServerRequest
	1, // 1: server.ServerService.Submit:output_type -> server.ServerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_proto_server_proto_init() }
func file_client_proto_server_proto_init() {
	if File_client_proto_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_server_proto_rawDesc), len(file_client_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_proto_server_proto_goTypes,
		DependencyIndexes: file_client_proto_server_proto_depIdxs,
		MessageInfos:      file_client_proto_server_proto_msgTypes,
	}.Build()
	File_client_proto_server_proto = out.File
	file_client_proto_server_proto_goTypes = nil
	file_client_proto_server_proto_depIdxs = nil
}
